<?php
$val1 = 5;
$val2 = 6;
echo"<br>";
echo"Apakah $val1 == $val2 ?";
echo $val1 == $val2;
echo"<br>";
echo"Apakah $val1 > $val2 ?";
echo $val1 > $val2;
echo"<br>";
echo"Apakah $val1 < $val2 ?";
echo $val1 < $val2;
echo"<br>";
echo"Apakah $val1 >= $val2 ?";
echo $val1 >= $val2;
echo"<br>";
echo"Apakah $val1 <= $val2 ?";
echo $val1 <= $val2;
echo"<br>";
echo"Apakah $val1 != $val2 ?";
echo $val1 != $val2;

$val1 = 5;
$val1 = 5;
echo"<br>";
echo"Apakah $val1 == $val2 ?";
echo $val1 == $val2;
echo"<br>";
echo"Apakah $val1 > $val2 ?";
echo $val1 > $val2;
echo"<br>";
echo"Apakah $val1 < $val2 ?";
echo $val1 < $val2;
echo"<br>";
echo"Apakah $val1 >= $val2 ?";
echo $val1 >= $val2;
echo"<br>";
echo"Apakah $val1 <= $val2 ?";
echo $val1 <= $val2;
echo"<br>";
echo"Apakah $val1 != $val2 ?";
echo $val1 != $val2;
echo"<br>";
?>